[package]
name = "rsq"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bytes = { version = "1", features = ["serde"] }
clap = { version = "4.1.4", features = ["env", "cargo"] }
fdlimit = "0.2.1"
futures = "0.3.26"
mimalloc = { version = "0.1.34", default-features = false }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
slotmap = "1.0.6"
tokio = { version = "1.25.0", features = ["full"] }
tokio-serde-cbor = "0.7.0"
tokio-stream = "0.1.11"
tokio-util = { version = "0.7.4", features = [ "codec" ] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = [ "parking_lot", "env-filter" ] }

[profile.release]
lto = true
